# Generated by Django 6.0.4 on 2026-05-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ESTIM - Inscription en Ligne', max_length=200)),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='form_assets/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_etablissement', models.CharField(max_length=255, verbose_name="ESTIM d'inscription")),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom(s)')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom(s)')),
                ('dob', models.DateField(verbose_name='Date de naissance')),
                ('pob', models.CharField(max_length=255, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationalite', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('tuteur', models.CharField(max_length=255, verbose_name='Nom du tuteur')),
                ('tel_tuteur', models.CharField(max_length=20, verbose_name='Tél. du tuteur')),
                ('civil', models.CharField(max_length=50, verbose_name='Statut matrimonial')),
                ('occupation', models.CharField(max_length=50, verbose_name='Occupation actuelle')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession / Métier')),
                ('bac_serie', models.CharField(max_length=50, verbose_name='Baccalauréat série')),
                ('bac_annee', models.CharField(max_length=10, verbose_name="Année d'obtention")),
                ('bac_etablissement', models.CharField(max_length=255, verbose_name='Établissement du BAC')),
                ('dernier_etab', models.CharField(max_length=255, verbose_name='Dernier établissement fréquenté')),
                ('dernier_annee', models.CharField(max_length=10, verbose_name='Année')),
                ('dernier_option', models.CharField(max_length=100, verbose_name='Option (Études précédentes)')),
                ('choix_cycle', models.CharField(max_length=100, verbose_name='Cycle souhaité')),
                ('choix_filiere', models.CharField(max_length=255, verbose_name='Filière principale')),
                ('alternative_filiere', models.CharField(blank=True, max_length=255, null=True, verbose_name='Filière alternative')),
                ('info_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Niveau en Informatique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
