# Generated by Django 6.0.4 on 2026-05-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formconfig',
            name='annee_academique',
            field=models.CharField(default='2025-2026', max_length=20, verbose_name='Année Académique'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='annee_academique',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Année Académique'),
        ),
    ]
