# Generated by Django 6.0.4 on 2026-05-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_formconfig_annee_academique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='inscriptions/photos/', verbose_name="Photo d'identité"),
        ),
    ]
