# Generated by Django 6.0.4 on 2026-06-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_inscription_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formconfig',
            name='app_download_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL de téléchargement App'),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='form_assets/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='qrcode_app',
            field=models.ImageField(blank=True, null=True, upload_to='form_assets/', verbose_name='QR Code App 1'),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='qrcode_app_alternative',
            field=models.ImageField(blank=True, null=True, upload_to='form_assets/', verbose_name='QR Code App 2'),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='school_address',
            field=models.TextField(default='91 rue Moulla, croisement av. de la Tsiemé — face Poste Réf / Rond-Point Koulounda — Brazzaville', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='school_agreement',
            field=models.CharField(default='Agrément N° 0238 /MES-CAB-DGESUP', max_length=255, verbose_name='Agrément'),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='school_name',
            field=models.CharField(default="ÉCOLE SUPÉRIEURE DE TECHNOLOGIE, D'INGÉNIERIE ET DE MANAGEMENT", max_length=255, verbose_name="Nom de l'école"),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='school_phone',
            field=models.CharField(default='06 966 48 98', max_length=100, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='school_website',
            field=models.URLField(default='http://www.estim-ecole.com', verbose_name='Site Web'),
        ),
        migrations.AddField(
            model_name='formconfig',
            name='school_whatsapp',
            field=models.CharField(default='+242 05 559 87 27', max_length=100, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='formconfig',
            name='side_image',
            field=models.ImageField(blank=True, null=True, upload_to='form_assets/', verbose_name='Image latérale (Web)'),
        ),
    ]
