# Generated by Django 6.0.4 on 2026-06-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_formconfig_app_download_url_formconfig_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='student_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='ID Étudiant'),
        ),
    ]
