# Generated by Django 6.0.4 on 2026-05-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='annonces/'),
        ),
    ]
