# Generated by Django 6.0.4 on 2026-05-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_annonce_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
