# Generated by Django 6.0.4 on 2026-05-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_alter_annonce_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='created_at',
        ),
    ]
