# Generated by Django 6.0.4 on 2026-05-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_heroimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom_etudiant', models.CharField(max_length=200)),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=4)),
                ('admis', models.BooleanField(default=False)),
                ('details_notes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
