# Generated by Django 6.0.4 on 2026-05-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_alter_examen_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='type',
            field=models.CharField(choices=[('Examen', 'Examen'), ('Devoir', 'Devoir'), ('Rattrapage', 'Rattrapage'), ('Session', 'Session'), ('Autres', 'Autres')], default='Examen', max_length=50),
        ),
    ]
