# Generated by Django 6.0.4 on 2026-05-01 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0011_alter_examen_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('results_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resultat',
            name='matricule',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='resultat',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='campus.sessionexamen'),
        ),
        migrations.AlterUniqueTogether(
            name='resultat',
            unique_together={('matricule', 'session')},
        ),
    ]
