# Generated by Django 6.0.4 on 2026-05-01 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0012_sessionexamen_alter_resultat_matricule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.sessionexamen'),
        ),
    ]
