# Generated by Django 6.0.4 on 2026-05-04 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0013_transaction_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_matricule', models.CharField(max_length=50, verbose_name='Matricule Payeur')),
                ('target_matricule', models.CharField(max_length=50, verbose_name='Matricule Cible')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence Paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Méthode de Paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Paiement')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.sessionexamen', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Paiement Réussi',
                'verbose_name_plural': 'Paiements Réussis',
            },
        ),
    ]
