# Generated by Django 6.0.4 on 2026-05-09 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0014_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.sessionexamen', verbose_name='Session'),
        ),
    ]
