# Generated by Django 6.0.4 on 2026-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0015_alter_paiement_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendrierAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'événement")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_important', models.BooleanField(default=False, verbose_name='Important')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calendrier Académique',
                'verbose_name_plural': 'Calendrier Académique',
                'ordering': ['date_debut'],
            },
        ),
    ]
