# Generated by Django 6.0.4 on 2026-06-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0016_calendrieracademique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nom du site')),
                ('url', models.URLField(max_length=500, verbose_name='URL du site')),
                ('icon_name', models.CharField(default='public', max_length=50, verbose_name="Nom de l'icône Material")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lien Site Web',
                'verbose_name_plural': 'Liens Sites Web',
            },
        ),
    ]
