# Generated by Django 6.0.4 on 2026-06-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0017_siteweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_matricule',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricule cible'),
        ),
    ]
