# Generated by Django 6.0.4 on 2026-06-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0018_notification_target_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name="Adresse de l'établissement"),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='agrement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Agrément de l'établissement"),
        ),
    ]
